export const portfolioData = [
  // Photography (5 programs)
  {
    id: 'photo1',
    title: 'Urban Echoes',
    category: 'photography',
    type: 'Digital Photography',
    year: '2025',
    description: 'A series of architectural photography exploring the relationship between light and their surrounding environment through the lens of a camera.',
    detailDescription: 'An exploration of urban architecture and its emotional resonance, capturing the interplay between light and shadow in Old Quebec. This photograph was taken during the golden hour when the ancient stone walls came alive with warm, dancing shadows that seemed to whisper stories of centuries past.',
    technique: 'Digital Photography with Natural Light',
    equipment: 'Canon EOS 6D, 15-35mm f/2.8 Lens',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Canon EOS 6D, 15-35mm f/2.8 Lens',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'I aimed to capture the duality of urban environments by using architectural reflections to blend built and natural spaces, creating a dialogue between human-made structures and their organic surroundings.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1ZFAwq9soEPUX87PrbjGc04u7wX1meSYW?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1GUqstoi4D6Mg-pSEvBlkqBKbtNOIoSW2?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1ceV_FZcj7p2hklBrnVktfNex5RBuQNO0?w=800&h=800'
  },
  {
    id: 'photo2',
    title: 'Morning Solitude',
    category: 'photography',
    type: 'Documentary Photography',
    year: '2025',
    description: 'Documentary portrait series focusing on the relationship between natural landscapes and human architecture.',
    detailDescription: 'Captured during golden hour, this piece examines the relationship between natural landscapes and human architecture through intimate framing. The soft morning light creates a dialogue between the organic curves of the landscape and the geometric precision of architectural elements.',
    technique: 'Natural Light Photography',
    equipment: 'Canon EOS RP, Kit Lens',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Canon EOS RP, Kit Lens',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Class Assignment - Mentor Challenge',
    designIntentions: 'My goal was to showcase the relationship of nature and architecture by using photogrpahy as a storyteller, using dramatic lighting to emphasize character while maintaining an intimate, insightful perspective.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1Cm-uf2NKLUCgj_IKaglS4KLj_RRxR7FH?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1STf7QNiTasnAuTXkGuO0VnyoxLhXDAoC?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1WBTZBJJS_z9yoUTBSiVmvvoKUpnCk6BB?w=800&h=800'
  },
  {
    id: 'photo3',
    title: 'Photographic Stories',
    category: 'photography',
    type: 'Narrative Photography',
    year: '2025',
    description: 'A collection of images crafted to tell compelling visual stories, where each photograph serves as a chapter in a larger narrative about place, emotion, and memory.',
    detailDescription: 'This project explores the art of visual storytelling through photography, where each image is carefully composed to convey a complete narrative. Shot at the Getty and various locations, these photographs demonstrate how architectural spaces, lighting, and human elements can combine to create powerful stories without words. The aim was to shoot images that told a story — capturing not just moments, but entire emotional journeys within single frames.',
    technique: 'Narrative Photography & Visual Storytelling',
    equipment: 'Nikon D3300, 50-200mm f/2.8',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Nikon D3300, 50-200mm f/2.8',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'The goal was to create photographs that function as visual narratives, using composition, light, and subject matter to tell stories that evoke nostalgia, cultural memory, and emotional resonance. Each image was designed to stand alone as a complete story while contributing to a larger narrative about the relationship between space, time, and human experience.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1ue_9K2E3gPDDZVBfChsnkNCaNFmhNM1P?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1kyankMvgQZJNanrmFi4dG682ydT37vqP?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1Xz00lSySWY3NkKFd8U2ofP5dKqw9gLxg?w=800&h=800'
  },
  {
    id: 'photo4',
    title: 'Hidden Art',
    category: 'photography',
    type: 'Street Photography',
    year: '2025',
    description: 'Candid street photography capturing the spontaneous poetry of urban life and human interaction in public spaces.',
    detailDescription: 'Part of a series exploring human expression and emotion through ancient and contemporary composition. This piece investigates the layers of meaning hidden within artistic representation, questioning what remains visible and what is obscured in the translation between different artistic mediums.',
    technique: 'Street Photography',
    equipment: 'Canon EOS RP, Kit Lens',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Canon EOS RP, Kit Lens',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'I aimed to capture the authentic, unposed moments that reveal the humanity and character of urban life, using natural light and compositions\\ to tell stories about art and history in the city.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1FDoupxA9w9JOytll4hIuGD_K1jFs0ynv?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/17tjR3UjtiuP8Pa8IcYTXw8yL65fVR8an?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1b6bfVw8q0KOPwckRDAiFZAN1z7YkZKV1?w=800&h=800'
  },

  // 3D Design (2 programs)
  {
    id: '3d1',
    title: 'Neptune',
    category: '3d',
    type: '3D Architectural Visualization',
    year: '2025',
    description: 'A FIRST Robotics bot built me and my team 9477 Lambda.',
    detailDescription: 'A bot built under a tight budget as a rookie team. Neptune placed top twenty in the state, winning the Industrial Design reward for its innovative use of pneumatic pistons.',
    technique: '3D Modeling, Machining, Electrical Wiring, Documentation',
    equipment: 'Basic Mechanical Engineering tools',
    digitalTools: 'On-Shape, Adobe Illustrator, Canva, Github',
    physicalTools: 'Desktops, Basic Engineering Tools',
    originalSize: '28" x 28"',
    medium: '3D Digital Rendering, Physical Build',
    assignmentStatus: 'Class Assignment - Club',
    designIntentions: 'My job was to prototype and build Neptunes dealge system. When designing neptune, we aimed to set ourselves apart by using pneumatic pistons, something thats very rare to see in a FIRST Robotics Bot.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1Cra0jeg4ONj5UaZEdVZyPuSQDzgRN7wi?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1a2Fff0Ok_rJt4TD6z2gCAjyBBwQJSyKk?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1YezSSLf_8wwo7uACSNLFs5YI495NfaZG?w=800&h=800'
  },
  {
    id: '3d2',
    title: 'USS Midway',
    category: 'photography',
    type: 'Maritime Photography',
    year: '2025',
    description: 'A photographic exploration of the USS Midway Museum, capturing the historic aircraft carrier\'s architecture, naval aircraft, and maritime heritage.',
    detailDescription: 'This photography series documents the USS Midway, America\'s longest-serving aircraft carrier of the 20th century. Shot aboard the museum ship in San Diego Harbor, these images capture the vessel\'s imposing architecture, vintage naval aircraft, and the stories embedded in its steel corridors.',
    technique: 'Maritime & Architectural Photography',
    equipment: 'Canon EOS RP, 24-70mm f/2.8 Lens',
    digitalTools: 'Adobe Lightroom Classic, Adobe Photoshop',
    physicalTools: 'Canon EOS RP, 24-70mm f/2.8 Lens, Tripod',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'My goal was to document the USS Midway not just as a museum piece, but as a living testament to naval history. I focused on capturing the geometric patterns of the flight deck and the weathered textures of vintage aircraft. The photography aims to transport viewers aboard this historic carrier and convey the awe-inspiring scale of naval aviation during the Cold War era.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1Qrpbj1_GymLW2aj7voNqo-l-bKhAPkeu?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1q0fX_Maq9YUpKxSknc-sV6KJlWQnAdcW?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1VJTzXKHG_d1KePuKFzFjEWZJDaIBTM9i?w=800&h=800'
  },

  // 2D Design (3 programs)
  {
    id: '2d1',
    title: 'Meridian Collection',
    category: '2d',
    type: 'Social Media Design Account',
    year: '2025',
    description: 'Complete social media account made up of a team of 4 people creating designs and showing off their passions.',
    detailDescription: 'This social media account was made by a group of 4 people who specialized in Graphic Design, Photography, and Videography.',
    technique: 'Graphic Design, Photography, and Videography',
    equipment: 'Adobe Illustrator, Photoshop, Adobe Premiere Pro',
    digitalTools: 'Adobe Illustrator, Adobe Photoshop, Adobe Premiere Pro',
    physicalTools: 'Desktops and Laptops',
    originalSize: 'Instagram Social Media Page',
    medium: 'Instagram',
    assignmentStatus: 'Passion Project',
    designIntentions: 'Meridian Collection started off as a small little joke that a group of friends started but then shifted into a full fledged account noticed by the Georgia DECA Instagram Page and The Getty Instagram Page. We grew this page from a small account meant as a joke to a account with a couple hundred followers.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/159m7eiY29850XVVaRO3zPUdQesYoQfwB?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1I8CWI-wHN_if9gC8fKVxATb1XXIvIlmX?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1fyKZy0iLhsjpAvBmCcudLnC5xelwj7dR?w=800&h=800'
  },
  {
    id: '2d2',
    title: 'Mythic Wordage',
    category: '2d',
    type: 'Graphic Design',
    year: '2025',
    description: 'Artistic documentation of museum artifacts and exhibitions, exploring the intersection of history, art, and contemporary presentation.',
    detailDescription: 'This series of designs was made to showcase the beauty of the ordinary through mythological references and allusions to the stories of these mythologies..',
    technique: 'Graphic Design, Travel Photography',
    equipment: 'Canon EOS RP, 50mm f/1.8 Lens',
    digitalTools: 'Adobe Lightroom Classic, Adobe Illustrator',
    physicalTools: 'Canon EOS RP, 50mm f/1.8 Lens, Tripod',
    originalSize: '2" x 3" (Digital Print) 18" x 24" (Physical Print) ',
    medium: 'Poster Paper',
    assignmentStatus: 'Personal Project',
    designIntentions: 'I wanted to come up with some kind of thank you gift to my biology teacher, so I chose some words I thought were interesting and designed some posters based on the words and then shot background images and added graphics ontop of the image to create these posters.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1Fq6T_E-U47YK-K2gnGMiG6zF9kKXMSJ_?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1fpCTbowaPYm7nl667jpWyIoFhjW_ViOy?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1FIfIVCBWDvPSaBP7Up90Us7K2COXmL3r?w=800&h=800'
  },
  {
    id: '2d3',
    title: 'Windows XP Portfolio Website',
    category: '2d',
    type: 'Interactive Web Design',
    year: '2025',
    description: 'Comprehensive interactive portfolio website recreating the authentic Windows XP experience with modern web technologies and responsive design principles.',
    detailDescription: 'This ambitious web design project faithfully recreates the nostalgic Windows XP interface as a fully functional portfolio platform. The project demonstrates advanced frontend development skills, UI/UX design principles, and creative problem-solving by transforming a classic desktop operating system into an engaging web experience. Every detail from the authentic XP scrollbars to the taskbar animations was meticulously crafted to provide users with genuine nostalgia while showcasing professional work.',
    technique: 'Frontend Web Development and Interactive Design',
    equipment: 'React.js, TypeScript, Tailwind CSS, Figma Make Platform',
    digitalTools: 'React.js, TypeScript, Tailwind CSS v4, Motion/React, Figma, VS Code, Chrome DevTools',
    physicalTools: 'Laptop and Reference Screenshots from Windows XP',
    originalSize: 'Responsive Web Application (1920px+ Desktop Optimized)',
    medium: 'Interactive Web Application, Progressive Web App',
    assignmentStatus: 'Personal Portfolio Project',
    designIntentions: 'I aimed to create a unique portfolio experience that combines nostalgic appeal with modern functionality, demonstrating both technical proficiency and creative vision while paying homage to the beloved Windows XP interface that defined an era of computing.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1aFcDCIEg4EWP3a5g6wJ6cWeeOGv6g0Z-?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1tW2hGLD1JuJmBewOwtZhH16MfMH1FrzR?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1fsEJQlAgmDZ_ltDhbradHqezIEIzLEId?w=800&h=800'
  },
  {
    id: 'photo5',
    title: 'Pigon Productions',
    category: 'photography',
    type: 'Social Media Photogrpahy Account',
    year: '2025',
    description: 'Complete social media account made to host all my event details and as a means of contacting me.',
    detailDescription: 'This social media account was made as a means of contacting me for events, but eventually grew into much more with programs like the Snap Smarter September program',
    technique: 'Photography, Videography, and 2d Design',
    equipment: 'Canva, Adobe Lightroom, Adobe Premiere Pro, Sony a6700, and a Laptop',
    digitalTools: 'Canva, Adobe Lightroom, Adobe Premiere Pro',
    physicalTools: 'Desktops, Laptops, Sony a6700',
    originalSize: 'Instagram Social Media Page',
    medium: 'Instagram',
    assignmentStatus: 'Passion Project',
    designIntentions: 'Pigon Productions was meant as just a means of contacting me for events, but eventually grew into more than that with programs to teach followers how to take better photos.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1f4FbnZUSxYYSUME_4ViR40eFjg8Bz9Nu?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1-EQWQutqQHkf-KDqZAWwfQJrxX7T8PdY?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1M5tqbRXw-RjsOz6hzPRVPeOoW-KqSwIU?w=800&h=800'

  }
];
